### PR TITLE
Consume the `className` prop in OuiSearchBar

### LINKED ISSUE #1343: [BUG] Class name prop is not passed down for OuiSearchBar component
**Describe the bug**

The OuiSearchBar component extends commonprops which contains className and data-test-subj. These are necessary and are used by many plugins for testing and styling. The issue is even though these props are taken in by the OuiSearchBar, they aren't passed down or used in the rendered JSX components. 

**To Reproduce**
1. Use OuiSearchBar component to a render search bar in OSD/ any OSD plugin
2. Add a class name prop example: 
``` 
     <EuiSearchBar
        className="myclass"
        box={{
          placeholder: 'Search to filter Available Metrics',
          incremental: true,
        }}
        defaultQuery={''}
        query={searchText}
        onChange={onChange}
      />
```
3. Go to browser inspect the search bar component to check class. 
4. See the class name isn't propogated
Screenshot 2024-08-14 at 1 42 27 PM

**Expected behavior**
The class names should be propagated to the child components

**Host/Environment (please complete the following information):**
 - OUI Version: 1.9.0
 - OSD Version (if applicable): 3.0.0
 - OS: Mac OS
 - Browser and version Firefox

**Additional context**

### PR DESCRIPTION
**Pull request by AMoo-Miki**
### Description
Consume the `className` prop in OuiSearchBar

Also:
* deprecate `aria-label` and `data-test-subj` which have never been consumed despite being defined

### Issues Resolved
Fixes #1343

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] All tests pass
  - [ ] `yarn lint`
  - [ ] `yarn test-unit`
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/components/search_bar/search_bar.tsx [hunk 1]
```diff
@@ -99,6 +99,12 @@ export interface OuiSearchBarProps extends CommonProps {
   dateFormat?: object;
 
   compressed?: boolean;
+
+  // @deprecated This property has never been consumed despite being defined
+  'aria-label'?: string;
+
+  // @deprecated This property has never been consumed despite being defined
+  'data-test-subj'?: string;
```
Comment (ashwin-pc) [inline src/components/search_bar/search_bar.tsx:107]: do we still have a `data-test-subj` that we can use? for our tests?

**Review by ashwin-pc — APPROVED** [review]

File: src/components/search_bar/search_bar.tsx (hunk 1 above)
Comment (AMoo-Miki) [reply src/components/search_bar/search_bar.tsx:107]: the actual component inside does and that one has its own test id. These two have never been attached to anything.
