### PR TITLE
[Fix] Add error handling when staged files are empty

### LINKED ISSUE #1071: [BUG] `scripts/test-staged.js` raise error when commit only include a Delete operation
**Describe the bug**

Reviewing the base code, I realised that when you commit new changes, `scripts/test-staged.js` only considers files that are _Added_, _Copied_, _Modified_ or _Renamed_ but never a _Deleted_. When trying to commit a change that only has a _Delete_, the variable `stagedFiles` is an empty list (`['']`) and then the testing command from jest with flag --findRelatedTests complains because no location is given.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a txt file in the root folder with some text (e.g: `Hello World`)
2. Add _Added_ changes in the staging area and the commit (`git add .` and `git -sm "adding random txt file`)
3. After the previous commit, Delete the txt file created.
4. Add _Delete_ changes in the staging area and the commit (`git add .` and `git -sm "adding random txt file`)
5. See error.

**Expected behavior**

When committing you should not see an error from jest as described below

**Error Message**

```sh
Here below is the error I get:

oui git:(docs/modal-width) ✗ git commit -sm "removing file modal_width.js"
yarn run v1.22.19
$ yarn tsc --noEmit && yarn lint-es && yarn lint-sass
$ '/Users/samuel/Project Code/OpenSearch_Initiative_Programme/oui/node_modules/.bin/tsc' --noEmit
$ eslint --cache "{src,src-docs}/**/*.{ts,tsx,js}" --max-warnings 0
$ sass-lint -v --max-warnings 0
:sparkles:  Done in 8.29s.
yarn run v1.22.19
$ cross-env NODE_ENV=test jest --config ./scripts/jest/config.json --findRelatedTests
Usage: jest [--config=<pathToConfigFile>] [TestPathPattern]

Options:
    ...<Set of Options>

Documentation: https://jestjs.io/

The --findRelatedTests option requires file paths to be specified.
Example usage: jest --findRelatedTests ./src/source.js ./src/index.js.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
node:child_process:960
    throw err;
    ^

Error: Command failed: yarn test-unit --findRelatedTests 
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Object.<anonymous> (/Users/samuel/Project Code/OpenSearch_Initiative_Programme/oui/scripts/test-staged.js:20:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 91528,
  stdout: null,
  stderr: null
}

Node.js v18.16.0
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `test-staged`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit:
```

**Host/Environment (please complete the following information):**
 - OUI Version: 1.3.0
 - OS: macOS Ventura 13.5.2

### PR DESCRIPTION
**Pull request by Willie-The-Lord**
### Description

- Add error handling when stagedFiles are empty

### Issues Resolved

Closes #1071

### Host/Environment
- OUI Version: 1.3.0
- OS: macOS Sonoma 14.0

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [x] `yarn lint`
  - [x] `yarn test-unit`
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Willie-The-Lord** [comment]
The original code omitted the `-D` flag in the `git diff` command because `scripts/test-staged.js` is designed to test only staged files that haven't been deleted ( If the file is deleted, then no need to test it... ). The main problem leading to issue #1071 is when the list of staged files is empty, returning `['']`, which in turn triggers the error.

File: scripts/test-staged.js [hunk 1]
```diff
@@ -14,9 +14,12 @@ const { execSync } = require('child_process');
 // find names of staged files
 const stagedFiles = execSync('git diff --cached --name-only --diff-filter=ACMR')
```
Comment (BigSamu) [inline scripts/test-staged.js:15]: @Willie-The-Lord, you are not adding a D in the filter as suggested by @BSFishy. Check the comment [here](https://github.com/opensearch-project/oui/issues/1071#issuecomment-1755752789)

**Review by BigSamu — CHANGES_REQUESTED** [review]
@Willie-The-Lord,

When running locally the changes you did, I got the error below by just adding a txt file called `Hello.txt` with some text inside in root. Are you sure you are using the latest version of OUI? When working on the main and doing the same changes, I do not get that error.

```sh
➜  oui git:(issue1071) git status                                                                                                  [🐍 system]
On branch issue1071
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        Hello.txt

nothing added to commit but untracked files present (use "git add" to track)
➜  oui git:(issue1071) ✗ git add .                                                                                                 [🐍 system]
➜  oui git:(issue1071) ✗ git status                                                                                                [🐍 system]
On branch issue1071
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   Hello.txt

➜  oui git:(issue1071) ✗ git commit -sm "Hello World"                                                                              [🐍 system]
yarn run v1.22.19
$ yarn tsc --noEmit && yarn lint-es && yarn lint-sass
$ /Users/samuel/Project_Code/OpenSearch_Initiative_Programme/oui/node_modules/.bin/tsc --noEmit
src-docs/src/components/guide_section/guide_section.tsx:138:16 - error TS2339: Property 'MSInputMethodContext' does not exist on type 'Window & typeof globalThis'.

138       !!window.MSInputMethodContext &&
                   ~~~~~~~~~~~~~~~~~~~~

src/components/datagrid/data_grid_inmemory_renderer.tsx:142:42 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

142           onCellRender(rowIndex, column, getElementText(cellDiv))
                                             ~~~~~~~~~~~~~~~~~~~~~~~

src/components/datagrid/data_grid_inmemory_renderer.tsx:155:38 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

155       onCellRender(rowIndex, column, getElementText(cellDiv));
                                         ~~~~~~~~~~~~~~~~~~~~~~~

src/components/date_picker/super_date_picker/date_popover/date_popover_content.tsx:154:7 - error TS2322: Type 'string' is not assignable to type 'undefined'.

154       autoFocus="selected"
          ~~~~~~~~~

  node_modules/@types/react/index.d.ts:1850:9
    1850         autoFocus?: boolean | undefined;
                 ~~~~~~~~~
    The expected type comes from property 'autoFocus' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<OuiTabbedContent> & Pick<Readonly<OuiTabbedContentProps> & Readonly<...>, "color" | ... 264 more ... | "onTabClick"> & InexactPartial<...> & InexactPartial<...>'

src/components/header/header_links/header_links.tsx:98:20 - error TS2525: Initializer provides no value for this binding element and the binding element has no default value.

98   const { onClick: _onClick, iconType = 'apps', ...popoverButtonRest } = {
                      ~~~~~~~~

src/components/header/header_links/header_links.tsx:98:20 - error TS7031: Binding element '_onClick' implicitly has an 'any' type.

98   const { onClick: _onClick, iconType = 'apps', ...popoverButtonRest } = {
                      ~~~~~~~~

src/components/icon/icon.test.tsx:63:9 - error TS2794: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?

63         resolve();
           ~~~~~~~~~

  node_modules/typescript/lib/lib.es2015.promise.d.ts:33:34
    33     new <T>(executor: (resolve: (value: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'value' was not provided.

src/components/list_group/pinnable_list_group/pinnable_list_group.tsx:118:11 - error TS2774: This condition will always return true since this function is always defined. Did you mean to call it instead?

118       if (onPinClick && !itemProps.extraAction && pinnable) {
              ~~~~~~~~~~

src/components/markdown_editor/markdown_editor.tsx:258:7 - error TS2345: Argument of type '() => [vfile.VFile, null] | [null, unknown]' is not assignable to parameter of type '() => [any, OuiMarkdownParseError | null]'.
  Type '[VFile, null] | [null, unknown]' is not assignable to type '[any, OuiMarkdownParseError | null]'.
    Type '[null, unknown]' is not assignable to type '[any, OuiMarkdownParseError | null]'.
      Type at position 1 in source is not compatible with type at position 1 in target.
        Type 'unknown' is not assignable to type 'OuiMarkdownParseError | null'.

258     >(() => {
          ~~~~~~~

src/components/search_bar/query/default_syntax.ts:357:73 - error TS2571: Object is of type 'unknown'.

357         `Invalid value \`${expression}\` set for field \`${field}\` - ${e.message}`,
                                                                            ~

src/components/search_bar/search_bar.tsx:192:36 - error TS2571: Object is of type 'unknown'.

192       const error: Error = { name: e.name, message: e.message };
                                       ~

src/components/search_bar/search_bar.tsx:192:53 - error TS2571: Object is of type 'unknown'.

192       const error: Error = { name: e.name, message: e.message };
                                                        ~

src/components/selectable/selectable_templates/selectable_template_sitewide.tsx:252:7 - error TS2322: Type '{ onFocus: (e: React.FocusEvent<HTMLInputElement, Element>) => void; onBlur: (e: React.FocusEvent<HTMLInputElement, Element>) => void; ... 299 more ...; isPreFiltered?: boolean | undefined; }' is not assignable to type 'Partial<OuiSelectableSearchProps<{ className: string; prepend: ReactNode; append: ReactNode; icon?: OuiIconProps | undefined; avatar?: OuiAvatarProps | undefined; ... 266 more ...; onTransitionEndCapture?: TransitionEventHandler<...> | undefined; } | { ...; }>>'.
  Types of property 'options' are incompatible.
    Type '((DisambiguateSet<OuiSelectableGroupLabelOption<{ [key: string]: any; }>, OuiSelectableLIOption<{ [key: string]: any; }>> & CommonProps & { ...; } & HTMLAttributes<...> & { ...; }) | (DisambiguateSet<...> & ... 3 more ... & { ...; }))[] | undefined' is not assignable to type '((DisambiguateSet<Omit<OuiSelectableOptionBase, "isGroupLabel"> & HTMLAttributes<HTMLDivElement> & { isGroupLabel: true; } & { ...; }, CommonProps & ... 2 more ... & { ...; }> & CommonProps & { ...; } & HTMLAttributes<...> & { ...; }) | (DisambiguateSet<...> & ... 3 more ... & { ...; }))[] | undefined'.
      Type '((DisambiguateSet<OuiSelectableGroupLabelOption<{ [key: string]: any; }>, OuiSelectableLIOption<{ [key: string]: any; }>> & CommonProps & { ...; } & HTMLAttributes<...> & { ...; }) | (DisambiguateSet<...> & ... 3 more ... & { ...; }))[]' is not assignable to type '((DisambiguateSet<Omit<OuiSelectableOptionBase, "isGroupLabel"> & HTMLAttributes<HTMLDivElement> & { isGroupLabel: true; } & { ...; }, CommonProps & ... 2 more ... & { ...; }> & CommonProps & { ...; } & HTMLAttributes<...> & { ...; }) | (DisambiguateSet<...> & ... 3 more ... & { ...; }))[]'.
        Type '(DisambiguateSet<OuiSelectableGroupLabelOption<{ [key: string]: any; }>, OuiSelectableLIOption<{ [key: string]: any; }>> & CommonProps & { ...; } & HTMLAttributes<...> & { ...; }) | (DisambiguateSet<...> & ... 3 more ... & { ...; })' is not assignable to type '(DisambiguateSet<Omit<OuiSelectableOptionBase, "isGroupLabel"> & HTMLAttributes<HTMLDivElement> & { isGroupLabel: true; } & { ...; }, CommonProps & ... 2 more ... & { ...; }> & CommonProps & { ...; } & HTMLAttributes<...> & { ...; }) | (DisambiguateSet<...> & ... 3 more ... & { ...; })'.
          Type 'DisambiguateSet<OuiSelectableGroupLabelOption<{ [key: string]: any; }>, OuiSelectableLIOption<{ [key: string]: any; }>> & CommonProps & { ...; } & HTMLAttributes<...> & { ...; }' is not assignable to type '(DisambiguateSet<Omit<OuiSelectableOptionBase, "isGroupLabel"> & HTMLAttributes<HTMLDivElement> & { isGroupLabel: true; } & { ...; }, CommonProps & ... 2 more ... & { ...; }> & CommonProps & { ...; } & HTMLAttributes<...> & { ...; }) | (DisambiguateSet<...> & ... 3 more ... & { ...; })'.
            Type 'DisambiguateSet<OuiSelectableGroupLabelOption<{ [key: string]: any; }>, OuiSelectableLIOption<{ [key: string]: any; }>> & CommonProps & { ...; } & HTMLAttributes<...> & { ...; }' is not assignable to type 'DisambiguateSet<Omit<OuiSelectableOptionBase, "isGroupLabel"> & HTMLAttributes<HTMLDivElement> & { isGroupLabel: true; } & { ...; }, CommonProps & ... 2 more ... & { ...; }> & CommonProps & { ...; } & HTMLAttributes<...> & { ...; }'.
              Type 'DisambiguateSet<OuiSelectableGroupLabelOption<{ [key: string]: any; }>, OuiSelectableLIOption<{ [key: string]: any; }>> & CommonProps & { ...; } & HTMLAttributes<...> & { ...; }' is not assignable to type '{ className: string; prepend: React.ReactNode; append: React.ReactNode; icon?: OuiIconProps | undefined; avatar?: OuiAvatarProps | undefined; ... 266 more ...; onTransitionEndCapture?: React.TransitionEventHandler<...> | undefined; }'.
                Types of property 'className' are incompatible.
                  Type 'string | undefined' is not assignable to type 'string'.
                    Type 'undefined' is not assignable to type 'string'.

252       searchProps={{
          ~~~~~~~~~~~

  src/components/selectable/selectable.tsx:78:5
    78     searchProps?: Partial<OuiSelectableSearchProps<T>>;
           ~~~~~~~~~~~
    The expected type comes from property 'searchProps' which is declared here on type 'IntrinsicAttributes & (IntrinsicClassAttributes<OuiSelectable<{ className: string; prepend: ReactNode; append: ReactNode; icon?: OuiIconProps | undefined; ... 267 more ...; onTransitionEndCapture?: TransitionEventHandler<...> | undefined; } | { ...; }>> & ((Pick<...> & ... 1 more ... & InexactPartial<...>) | (Pick<....'

src/components/suggest/suggest_item.tsx:196:9 - error TS2783: 'onClick' is specified more than once, so this usage will be overwritten.

196         onClick={onClick}
            ~~~~~~~~~~~~~~~~~

  src/components/suggest/suggest_item.tsx:198:9
    198         {...(rest as PropsForButton)}>
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    This spread always overwrites this property.

src/components/tabs/tabbed_content/tabbed_content.test.tsx:111:31 - error TS2322: Type '"initial" | "selected"' is not assignable to type 'undefined'.
  Type '"initial"' is not assignable to type 'undefined'.

111             <OuiTabbedContent autoFocus={focusType} tabs={tabs} />
                                  ~~~~~~~~~

  node_modules/@types/react/index.d.ts:1850:9
    1850         autoFocus?: boolean | undefined;
                 ~~~~~~~~~
    The expected type comes from property 'autoFocus' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<OuiTabbedContent> & Pick<Readonly<OuiTabbedContentProps> & Readonly<...>, "color" | ... 264 more ... | "onTabClick"> & InexactPartial<...> & InexactPartial<...>'


Found 15 errors in 12 files.

Errors  Files
     1  src-docs/src/components/guide_section/guide_section.tsx:138
     2  src/components/datagrid/data_grid_inmemory_renderer.tsx:142
     1  src/components/date_picker/super_date_picker/date_popover/date_popover_content.tsx:154
     2  src/components/header/header_links/header_links.tsx:98
     1  src/components/icon/icon.test.tsx:63
     1  src/components/list_group/pinnable_list_group/pinnable_list_group.tsx:118
     1  src/components/markdown_editor/markdown_editor.tsx:258
     1  src/components/search_bar/query/default_syntax.ts:357
     2  src/components/search_bar/search_bar.tsx:192
     1  src/components/selectable/selectable_templates/selectable_template_sitewide.tsx:252
     1  src/components/suggest/suggest_item.tsx:196
     1  src/components/tabs/tabbed_content/tabbed_content.test.tsx:111
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `test-staged`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 
```

File: scripts/test-staged.js (hunk 1 above)
Comment (Willie-The-Lord) [reply scripts/test-staged.js:15]: @BigSamu Since your issue is happening in OUI version 1.3, this PR is specifically for version 1.3. The issue is resolved in the the latest version. Please checkout [this PR](https://github.com/opensearch-project/oui/pull/1072). If you still run into any problem, please let me know!

Comment (BigSamu) [reply scripts/test-staged.js:15]: Baaaaa, sorry you right @Willie-The-Lord. I forgot this problem was from OUI v1.3. However, I am still getting the same errors in the PR you did. Is it working correctly from your side? Also, did you check my comment above for adding the D filter as @BSFishy suggested?

Comment (Willie-The-Lord) [reply scripts/test-staged.js:15]: @BigSamu Lemme check on my end for the error. Regarding the `-D` flag, I've provided the reason why the original code does not include`-D` in the previous comment. It seems reasonable to me. But welcome any other suggestion why adding `-D` is necessary.

Comment (BigSamu) [reply scripts/test-staged.js:15]: You right! Make sense in your comment above to not include the -D flag! OK, I wait for your check on your end.

Comment (Willie-The-Lord) [reply scripts/test-staged.js:15]: Ah! I think that the issue with your console output isn't related to `scripts/test-staged.js`. The problem arises because the dependencies in OUI v1.3 differ from those in the latest OUI version. Could you please run `yarn` in your terminal again, and then reproduce the following steps `git add . && git commit -sm "test.txt"`?

**Review by BigSamu — APPROVED** [review]
LGTM! @BSFishy already reviewed and changes are OK!

File: CHANGELOG.md [hunk 2]
```diff
@@ -16,6 +16,7 @@
 - Adjust background color of OuiToolTip in `next` theme ([#1004](https://github.com/opensearch-project/oui/pull/1004))
 - Add new `middle-out` order prop option to `OuiPaletteColorBlind` ([#856](https://github.com/opensearch-project/oui/pull/856))
 - Add new icons for OpenSearch Dashboards v2.10.0 ([#1014](https://github.com/opensearch-project/oui/pull/1014))
+- Add error handling when staged files are empty([#1114](https://github.com/opensearch-project/oui/pull/1114))
```
Comment (joshuarrrr) [inline CHANGELOG.md:19]: nit - Can you move this to the "Infrastructure" section? (And also add a space before `(`)

**Review by joshuarrrr — APPROVED** [review]
LGTM, but a minor request on the changelog entry.

**Review by AMoo-Miki — APPROVED** [review]
