### PR TITLE
[Fix] "Guidelines" Documentation Render Blank Page

### LINKED ISSUE #1109: [BUG] "Guidelines" Documentation Render Blank Page
**Describe the bug**

When navigating to the Source Documentation page and clicking on either the "Colors" or "Sass" sections, both render blank pages instead of displaying the relevant documentation.

**To Reproduce**

1. On the side nav, click on either "Colors" or "Sass"
3. Observe that both pages render blank page

**Expected behavior**

Upon clicking on "Colors" or "Sass", users should be able to see the corresponding documentation for these sections instead of a blank page.

**Screenshots**

https://github.com/opensearch-project/oui/assets/65143821/6ab9b421-eeb1-4a55-bad4-46d4c4db3096

### PR DESCRIPTION
**Pull request by Willie-The-Lord**
### Description

Resolve the issue where the Source Documentation would render blank pages when users clicked on either the "Colors" or "Sass" sections.

### Issues Resolved

Closes #1109 

#### Before

https://github.com/opensearch-project/oui/assets/65143821/8f09f867-b4f0-411f-aa1c-b147810405f1

#### After

https://github.com/opensearch-project/oui/assets/65143821/8ecd4720-4751-4221-ba0e-228354ac9bb5

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [x] `yarn lint`
  - [x] `yarn test-unit`
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Willie-The-Lord** [comment]
While investigating this issue, I found it challenging to identify the bug due to the implicit typing of variables. 

For example, the main issue lies in the fact that `palette[color]` is already a `string` in the format "#017D73". Therefore, the original code `rgbToHex(palette[color].rgba).toUpperCase()` is unnecessary and prone to errors.

Do we have any plans to migrate some of these files to TypeScript for better type safety?

File: src-docs/src/views/guidelines/colors/vis_palette.js [hunk 1]
```diff
@@ -21,9 +21,9 @@ import {
   OuiText,
   OuiPanel,
 } from '../../../../../src/components';
-import { rgbToHex } from '../../../../../src/services';
 
 export const VisPalette = ({ variant }) => {
+  // TODO: Make this dynamic once we have ouiPaletteColorBlind in the dark and next-dark theme
```
Comment (BSFishy) [inline src-docs/src/views/guidelines/colors/vis_palette.js:26]: If I'm not mistaken, this is intentionally not changed between themes and just provides Scss access to the variables generated by https://oui.opensearch.org/1.3/#/utilities/color-palettes

Comment (BSFishy) [reply src-docs/src/views/guidelines/colors/vis_palette.js:26]: Looping in @kgcreative for more context

**Review by BSFishy — APPROVED** [review]

**Comment by vvavdiya** [comment]
@Willie-The-Lord 
PR details need to update in CHANGELOG.md

**Review by vvavdiya — COMMENTED** [review]
@Willie-The-Lord
PR details need to update in CHANGELOG.md

**Comment by Willie-The-Lord** [comment]
> @Willie-The-Lord PR details need to update in CHANGELOG.md

Thank you for the heads up!

File: src-docs/src/views/guidelines/colors/_utilities.js [hunk 2]
```diff
@@ -151,8 +152,8 @@ color: $${foreground};`;
             onClickAriaLabel="Click to copy SASS configurations"
             disabled={!contastIsAcceptableToCopy}
             style={{
-              backgroundColor: palette[background].rgba,
-              color: palette[foreground].rgba,
+              backgroundColor: palette[background],
+              color: palette[foreground],
```
Comment (BigSamu) [inline src-docs/src/views/guidelines/colors/_utilities.js:156]: @Willie-The-Lord, should not be here rgba values? Although I think is not a big deal, because the result is the same. I suppose that that property .rgba was a string in the format "rgba(<0-255>,<0-255>,<0-255>,<0-1>).

Just saying to keep consistency with what there was before. However, I don't see any utility function that returns the equivalent format for RGBA, just one for converting a HEX to RGB, but in array format.

**Review by BigSamu — APPROVED** [review]
Appart from the comment I did that is minor, the changes LGTM! I have already reviewed the code and tested it locally. Indeed the problem was tricky as @Willie-The-Lord mentioned.

**Comment by BigSamu** [comment]
@BSFishy,

Additionally I want to comment the following when doing `console.log(palette)` for the aux function `getSassVars(theme)` in the file `src-docs/src/views/guidelines/_get_sass_vars.js`

Why do we repeat the colour themes using variables that have the suffix `Text`. For example, take a look at the screenshot below. We are repeating the values for hex colour`"#F66"` in the keys`euiDangerColor` and `euiDangerColorText`. In both cases, the value is a string. Shouldn't we avoid DRY?

image

File: src-docs/src/views/guidelines/colors/_utilities.js (hunk 2 above)
Comment (Willie-The-Lord) [reply src-docs/src/views/guidelines/colors/_utilities.js:156]: Hi @BigSamu, I've just re-run the original code and `palette[background].rgba` is causing the render error as I mentioned in previous comments. This is because `palette[background]` returns a `string`, which does not have an `.rgba` property.

#### ❌ `palette[background].rgba`
Screenshot 2023-10-25 at 1 16 29 PM

#### ✅ `palette[background]`
Screenshot 2023-10-25 at 1 15 55 PM

Comment (BigSamu) [reply src-docs/src/views/guidelines/colors/_utilities.js:156]: I know! What I am trying to say is that the code was using RGBA format before and maybe for something (I don't know). That is why I suggest sticking with that format instead of HEX format. Make sense? However, you will need to build utility functions for getting RGBA values. It is just for consistency. 

Of course, It is a really minor issue. Your solution is much more simple and straightforward.

Comment (Willie-The-Lord) [reply src-docs/src/views/guidelines/colors/_utilities.js:156]: Ah, I understand now. I can also take on the task of building the utility function. @BSFishy , do you have any thoughts or suggestions on this?

**Comment by BSFishy** [comment]
> While investigating this issue, I found it challenging to identify the bug due to the implicit typing of variables.
> 
> For example, the main issue lies in the fact that `palette[color]` is already a `string` in the format "#017D73". Therefore, the original code `rgbToHex(palette[color].rgba).toUpperCase()` is unnecessary and prone to errors.
> 
> Do we have any plans to migrate some of these files to TypeScript for better type safety?

Unfortunately, not really. These variables are extracted from Sass, using custom scripts: https://github.com/opensearch-project/oui/blob/main/scripts/babel/variables-from-scss/index.js and https://github.com/opensearch-project/oui/blob/main/scripts/lib/compile-scss-with-variables.js.

I think the format changed from

```ts
color: {
  r: string;
  g: string;
  b: string;
  a: string;
  rgba: string;
}
```

into

```ts
color: string
```

Which is where the errors come from. We might be able to add some sort of type safety by updating the Webpack plugin.

> Why do we repeat the colour themes using variables that have the suffix `Text`. For example, take a look at the screenshot below. We are repeating the values for hex colour`"#F66"` in the keys`euiDangerColor` and `euiDangerColorText`. In both cases, the value is a string. Shouldn't we avoid DRY?

To this point, the generates vars are just all of the Sass vars in the projects put into a JSON object. So for whatever reason we have these variables which are used in different ways, all just extracted and put into a single object.

**Comment by BigSamu** [comment]
> To this point, the generates vars are just all of the Sass vars in the projects put into a JSON object. So for whatever reason we have these variables which are used in different ways, all just extracted and put into a single object.

Just asking here if we should simplify the JSON object to avoid DRY. It does not make sense to have the same value for 2 distinct keys. Of course, this will mean refactoring the code in other parts.

Regards,

Samuel

**Comment by joshuarrrr** [comment]
> While investigating this issue, I found it challenging to identify the bug due to the implicit typing of variables.
> 
> For example, the main issue lies in the fact that `palette[color]` is already a `string` in the format "#017D73". Therefore, the original code `rgbToHex(palette[color].rgba).toUpperCase()` is unnecessary and prone to errors.
> 
> Do we have any plans to migrate some of these files to TypeScript for better type safety?

I don't think we have any overall issue for migrating OUI from JS to TS, but I think you could open one with this as an example of why it may be worth the effort to do. The good thing about typescript conversions is that they can be parallelized and worked on as good first issues.

**Comment by joshuarrrr** [comment]
> > To this point, the generates vars are just all of the Sass vars in the projects put into a JSON object. So for whatever reason we have these variables which are used in different ways, all just extracted and put into a single object.
> 
> Just asking here if we should simplify the JSON object to avoid DRY. It does not make sense to have the same value for 2 distinct keys. Of course, this will mean refactoring the code in other parts.
> 
> Regards,
> 
> Samuel

@BigSamu This has to do with the way we use SASS vars in the project. In many cases, it's useful to have multiple aliases that map to different usages even if (in some themes) they actually use the same underlying value. When you look at the JSON file (or the output of `_get_sass_vars.js`), what you're seeing is the calculated/resolved values for each SASS var _in the currently selected theme_. But different themes (or even light/dark mode within a particular theme) may assign these values differently.

In your example, in that theme the `euiColorDanger` is suitable for use as a text color given the themed background colors, so it's not transformed by the `makeHighContrastColor()` function: https://github.com/search?q=repo%3Aopensearch-project%2Foui+ouiColorDangerText%3A&type=code

File: CHANGELOG.md [hunk 3]
```diff
@@ -18,6 +18,7 @@
 
 - Add exit code to compile-scss script on failure ([#1024](https://github.com/opensearch-project/oui/pull/1024))
 - Correct file path for import of Query component ([#1069](https://github.com/opensearch-project/oui/pull/1069))
+- Resolve "Guidelines" Documentation Render Blank Page ([#1111](https://github.com/opensearch-project/oui/pull/1111))
```
Comment (joshuarrrr) [inline CHANGELOG.md:21]:
```suggestion
- Fix "Guidelines" documentation links rendering blank pages ([#1111](https://github.com/opensearch-project/oui/pull/1111))
```

File: src-docs/src/views/guidelines/sass.js [hunk 4]
```diff
@@ -113,7 +112,7 @@ function renderPaletteColor(palette, color) {
       <OuiFlexItem grow={false}>
         <div
           className="guideSass__swatch"
-          style={{ background: rgbToHex(palette[color].rgba).toUpperCase() }}
+          style={{ background: palette[color] }}
```
Comment (joshuarrrr) [inline src-docs/src/views/guidelines/sass.js:115]: @Willie-The-Lord Is `palette[color]` already uppercased, or should we keep `.toUpperCase()` for consistency?

**Comment by Willie-The-Lord** [comment]
> > > To this point, the generates vars are just all of the Sass vars in the projects put into a JSON object. So for whatever reason we have these variables which are used in different ways, all just extracted and put into a single object.
> > 
> > 
> > Just asking here if we should simplify the JSON object to avoid DRY. It does not make sense to have the same value for 2 distinct keys. Of course, this will mean refactoring the code in other parts.
> > Regards,
> > Samuel
> 
> @BigSamu This has to do with the way we use SASS vars in the project. In many cases, it's useful to have multiple aliases that map to different usages even if (in some themes) they actually use the same underlying value. When you look at the JSON file (or the output of `_get_sass_vars.js`), what you're seeing is the calculated/resolved values for each SASS var _in the currently selected theme_. But different themes (or even light/dark mode within a particular theme) may assign these values differently.
> 
> In your example, in that theme the `euiColorDanger` is suitable for use as a text color given the themed background colors, so it's not transformed by the `makeHighContrastColor()` function: https://github.com/search?q=repo%3Aopensearch-project%2Foui+ouiColorDangerText%3A&type=code
> 
> But each theme is free to define the relationship between the `euiColorDanger` and `euiColorDangerText` variables (even hard-coding both), and OUI components are structured to use the appropriate variable whether the same or different.

Thanks @joshuarrrr  for the detailed explanation! It makes sense that the flexibility is beneficial, especially when we consider the implementation across various themes.

File: src-docs/src/views/guidelines/colors/vis_palette.js (hunk 1 above)
Comment (joshuarrrr) [reply src-docs/src/views/guidelines/colors/vis_palette.js:26]: Currently visualization colors are intentionally defined to be light/dark mode agnostic, but we do have plans to make them different between themes:  https://github.com/opensearch-project/oui/issues/818.

So I think we can remove the TODO from the comment for now:
```suggestion
  // ouiPaletteColorBlind() is currently shared across themes and dark/light modes. This will need to be  made dynamic once we have different visualization palettes as in https://github.com/opensearch-project/oui/issues/818
```

**Review by joshuarrrr — COMMENTED** [review]
Awesome fix @Willie-The-Lord - just a couple minor questions and suggestions.

File: src-docs/src/views/guidelines/sass.js (hunk 4 above)
Comment (Willie-The-Lord) [reply src-docs/src/views/guidelines/sass.js:115]: It's already uppercased.

Comment (Willie-The-Lord) [reply src-docs/src/views/guidelines/sass.js:115]: The hex color code originates from this location and is already in uppercase: https://github.com/Willie-The-Lord/oui/blob/issue1109/src/global_styling/variables/_colors.scss#L16 Should we still include `.toUpperCase()` as a precaution, in case the file changes in the future and potentially breaks something?

Comment (joshuarrrr) [reply src-docs/src/views/guidelines/sass.js:115]: nah, that's fine - thanks for the explanation

**Review by joshuarrrr — APPROVED** [review]

**Comment by BigSamu** [comment]
> > > To this point, the generates vars are just all of the Sass vars in the projects put into a JSON object. So for whatever reason we have these variables which are used in different ways, all just extracted and put into a single object.
> > 
> > 
> > Just asking here if we should simplify the JSON object to avoid DRY. It does not make sense to have the same value for 2 distinct keys. Of course, this will mean refactoring the code in other parts.
> > Regards,
> > Samuel
> 
> @BigSamu This has to do with the way we use SASS vars in the project. In many cases, it's useful to have multiple aliases that map to different usages even if (in some themes) they actually use the same underlying value. When you look at the JSON file (or the output of `_get_sass_vars.js`), what you're seeing is the calculated/resolved values for each SASS var _in the currently selected theme_. But different themes (or even light/dark mode within a particular theme) may assign these values differently.
> 
> In your example, in that theme the `euiColorDanger` is suitable for use as a text color given the themed background colors, so it's not transformed by the `makeHighContrastColor()` function: https://github.com/search?q=repo%3Aopensearch-project%2Foui+ouiColorDangerText%3A&type=code
> 
> But each theme is free to define the relationship between the `euiColorDanger` and `euiColorDangerText` variables (even hard-coding both), and OUI components are structured to use the appropriate variable whether the same or different.

Many thanks @joshuarrrr! Pretty clear the explanation!
